"""add server defaults to timestamps

Revision ID: 21f450323aa7
Revises: 1cc8106fb6c4
Create Date: 2026-05-11 03:59:43.847466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f450323aa7'
down_revision: Union[str, None] = '1cc8106fb6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
