"""add_updated_at_to_writing_samples

Revision ID: 9021d36391c2
Revises: 79bebe37ca2f
Create Date: 2026-05-11 04:27:37.054643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9021d36391c2'
down_revision: Union[str, None] = '79bebe37ca2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('writing_samples', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writing_samples', 'updated_at')
    op.drop_column('document_versions', 'updated_at')
    # ### end Alembic commands ###
